### ISSUE TITLE
how to activate

### ISSUE THREAD

**Issue by gautiermichelin** [hiroara/TiTestFairy#1]
Hi hiroara,

I've used gittio to register the TiTestFairy into my titanium project, but I still have "TESTFAIRY SDK NOT INTEGRATED IN BUILD, NO RECORDINGS WILL BE PERFORMED." on testfairy screen.

Did I miss something ?

Bye,

Gautier

**Comment by hiroara** [comment]
@gautiermichelin Hi gautiermichelin. Thanks for your report.

This module is need to pass app token on TestFairy as following. (You can get this token from account settings page.)

```
require('com.arihiro.titestfairy').begin(<YOUR_APP_TOKEN>);
```

After that, I think that your session is shown on TestFairy Dashboard.

Sorry for not writing this explanation in project. I'll update README later.

**Comment by gautiermichelin** [comment]
No problem for documentation, I'll test it in an hour or two.

I'll be more than happy to make you a pull request on README.md for the howto. That would be a very fair response to your quick answer :-)

**Comment by hiroara** [comment]
@gautiermichelin Thank you. I would be happy if you report the result.

**Comment by gautiermichelin** [comment]
I'm having problem downloading my build on testfairy this week-end, will see next week, sorry for the delay.

**Comment by hiroara** [comment]
@gautiermichelin Don’t worry about it. Thank you for your contribution!

**Comment by hiroara** [comment]
I'll close this issue. Please reopen if anything comes up.
